Update & Change deps & dev-deps to newest/alternative versions + no_std
dusk-network/Hades252 pull request #88
Opened 2021-04-16 10:54 UTC by CPerezz

- Updated bls & plonk to latest versions. Resolves: #84
- Replaced rand by rand-core. Resolved: #86
- Removed `anyhow` from dev-deps`. Resolves: #85
- Make repo no_std with `alloc` feature. Resolves: #87

Everything has been done on the same PR to since split the `no_std` and the version changes will have been more tricky since both relayed on each other.

2021-04-22 12:45 UTC, vlopes11 requested changes
Few nits

2021-04-22 12:45 UTC, vlopes11 commented on Cargo.toml
> +
Check format, unnecessary line break

2021-04-22 12:45 UTC, vlopes11 commented on src/lib.rs
> +#![no_std]
Why set the `no_std` also when `std` feature is used?

2021-04-27 10:40 UTC, ZER0 approved these changes
LGTM, but before merging ensure you edit the commit message for:
1. 12200e3ea4392293b710e6736b3c31af07e95f9d (too long and complex to be a summary) 
2. 0146baf592d91e953ecbf060ce3fe6138b9bd8d1 (do not start with a changelog verb)
3. fc8a4290c47a1555ef514512c51a55158f0ffc03 (do not start with a changelog verb)

Or you squash them.

2021-04-28 08:37 UTC, merged